win32 {
    HOMEDIR += $$(USERPROFILE)
}
else {
    HOMEDIR += $$(HOME)
}

INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/cores/arduino"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/variants/standard"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/__cores__/arduino/SPI/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/Ethernet/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/lib/OneWire_ID1"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/__cores__/arduino/EEPROM/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/__cores__/arduino/HID/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/__cores__/arduino/SoftwareSerial/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/__cores__/arduino/Wire/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/Adafruit_CircuitPlayground"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/Adafruit_CircuitPlayground/utility"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/Bridge/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/Esplora/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/Ethernet2/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/Firmata"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/Firmata/utility"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/GSM/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/Keyboard/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/LiquidCrystal/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/Mouse/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/RobotIRremote/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/Robot_Control/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/Robot_Motor/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/SD/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/Servo/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/SpacebrewYun/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/Stepper/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/TFT/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/Temboo/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/framework-arduinoavr/libraries/WiFi/src"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/toolchain-atmelavr/avr/include"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/toolchain-atmelavr/lib/gcc/avr/4.9.2/include"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/toolchain-atmelavr/lib/gcc/avr/4.9.2/include-fixed"
INCLUDEPATH += "$${HOMEDIR}/.platformio/packages/tool-unity"

DEFINES += "F_CPU=16000000L"
DEFINES += "PLATFORMIO=30504"
DEFINES += "ARDUINO_AVR_UNO"
DEFINES += "ARDUINO_ARCH_AVR"
DEFINES += "ARDUINO=10805"
DEFINES += "__AVR_ATmega328P__"

OTHER_FILES += platformio.ini

HEADERS += src/zeromqclient.h
SOURCES += src/options.cpp
HEADERS += src/rep.h
HEADERS += src/sub.h
HEADERS += src/singleton.h
SOURCES += src/zmq.cpp
HEADERS += src/pub.h
HEADERS += src/tools.h
HEADERS += src/list.h
HEADERS += src/map.h
HEADERS += src/context.h
SOURCES += src/socket.cpp
SOURCES += src/rep.cpp
HEADERS += src/socket_base.h
SOURCES += src/context.cpp
SOURCES += src/main.cpp
SOURCES += src/list.cpp
HEADERS += src/req.h
SOURCES += src/zeromqclient.cpp
HEADERS += src/zmq.h
SOURCES += src/pub.cpp
SOURCES += src/req.cpp
SOURCES += src/singleton.cpp
HEADERS += src/options.h
SOURCES += src/zeromqcommand.cpp
SOURCES += src/sub.cpp
HEADERS += src/zeromqcommand.h
SOURCES += src/socket_base.cpp
HEADERS += src/socket.h
SOURCES += src/map.cpp
HEADERS += src/Ethernet/IPAddress.h
SOURCES += src/Ethernet/EthernetServer.cpp
HEADERS += src/Ethernet/util.h
HEADERS += src/Ethernet/Dhcp.h
SOURCES += src/Ethernet/IPAddress.cpp
SOURCES += src/Ethernet/Dhcp.cpp
HEADERS += src/Ethernet/Ethernet2.h
HEADERS += src/Ethernet/EthernetUdp2.h
SOURCES += src/Ethernet/EthernetClient.cpp
HEADERS += src/Ethernet/EthernetServer.h
SOURCES += src/Ethernet/Ethernet2.cpp
SOURCES += src/Ethernet/EthernetUdp2.cpp
HEADERS += src/Ethernet/EthernetClient.h
HEADERS += src/Ethernet/utility/util.h
HEADERS += src/Ethernet/utility/SPI.h
SOURCES += src/Ethernet/utility/w5500.cpp
SOURCES += src/Ethernet/utility/socket.cpp
HEADERS += src/Ethernet/utility/w5500.h
SOURCES += src/Ethernet/utility/SPI.cpp
HEADERS += src/Ethernet/utility/socket.h
